# Generated by Django 4.0.6 on 2022-08-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_customer_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='صنعاء', max_length=200),
        ),
    ]
