# Generated by Django 4.0.6 on 2022-08-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='pictuers',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='صورة المنتج'),
        ),
    ]
