# Generated by Django 4.0.6 on 2022-08-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_pictuers_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictuers',
            name='product',
        ),
        migrations.AddField(
            model_name='pictuers',
            name='product',
            field=models.ManyToManyField(to='core.product'),
        ),
    ]
