# Generated by Django 4.0.6 on 2022-08-18 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_pictuers_product_pictuers_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictuers',
            name='product',
        ),
        migrations.AddField(
            model_name='pictuers',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name=' المنتج'),
        ),
    ]
